name: Build container
on:
  # Run on tag creation and on default branch
  push:
    tags:
      - v*
    branches:
      - main
  # Run automatically every Sunday at 5:00 AM
  schedule:
    - cron: 0 5 * * 0
  # Allow manual execution
  workflow_dispatch:

jobs:
  build:
    name: Build and push container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build docker container
        run: make docker-build
      - name: Log in to docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push container to registry
        run: make docker-push